repos:
-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.12.5
    hooks:
    -   id: ruff
        args: [--fix]
    -   id: ruff-format

-   repo: https://github.com/astral-sh/uv-pre-commit
    rev: 0.8.4
    hooks:
    -   id: pip-compile
        args: [-o, requirements.txt, pyproject.toml]
        files: ^(pyproject\.toml|uv\.lock|requirements\.txt)$
    -   id: pip-compile
        args: [-o, requirements-all.txt, pyproject.toml, --all-extras, --group, dev, --group, docs]
        files: ^(pyproject\.toml|uv\.lock|requirements-all\.txt)$